-- Slides 45-46: SQL semantics walkthrough
-- PostgreSQL 16+
DROP TABLE IF EXISTS R CASCADE;
DROP TABLE IF EXISTS S CASCADE;
CREATE TABLE R (A INTEGER);
CREATE TABLE S (B INTEGER, C INTEGER);
INSERT INTO R (A) VALUES (1), (3);
INSERT INTO S (B, C) VALUES
  (2, 3),
  (3, 4),
  (3, 5);
