-- Slides 59-62 and 115-119: R, S, and T
-- The slides name these relations but display no base rows.
-- PostgreSQL 16+
DROP TABLE IF EXISTS R CASCADE;
DROP TABLE IF EXISTS S CASCADE;
DROP TABLE IF EXISTS T CASCADE;
CREATE TABLE R (A INTEGER, B INTEGER);
CREATE TABLE S (A INTEGER, B INTEGER);
CREATE TABLE T (A INTEGER, B INTEGER);
